# Generated by Django 4.0.1 on 2022-05-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='home_header',
            field=models.CharField(default='Header', max_length=60),
        ),
        migrations.AddField(
            model_name='page',
            name='home_welcome',
            field=models.CharField(default='Welcome!', max_length=100),
        ),
    ]
